export { default as HomePage } from './HomePage';
export { default as LoginPage } from './LoginPage';
export { default as AboutPage } from './AboutPage';
export { default as ConsultationPage } from './ConsultationPage';
export { default as ContactPage } from './ContactPage';
export { default as EventsPage } from './EventsPage';
export { default as FAQPage } from './FAQPage';
export { default as ForumPage } from './ForumPage';
export { default as ReviewsPage } from './ReviewsPage';